### ISSUE TITLE
codec 'utf-8' 문제확인 부탁드립니다.

### ISSUE THREAD

**Issue by SeungJun9164** [haven-jeon/KoBART-chatbot#2]
kobart-chit chat.py를 다운받고 개인 컴퓨터에서 실행하기 위해 경로 설정을 모두 마친 상태입니다.  

실행코드를 실행하면서 아래와 같은 오류가 발생하였습니다.

Traceback (most recent call last):
  File "KoBART.py", line 300, in <module>
    model = KoBARTConditionalGeneration(args)
  File "KoBART.py", line 247, in __init__
    self.model = BartForConditionalGeneration.from_pretrained(self.hparams.model_path)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_utils.py", line 962, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 376, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 427, in get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 510, in _dict_from_json_file
    text = reader.read()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

디코딩 오류를 어떻게 해결해야 하는지 모르겠습니다. 
확인해주시면 감사하겠습니다.

**Comment by haven-jeon** [comment]
`self.hparams.model_path` 에 어떠한 곳이 지정되어 있는지 보시고, 그곳의 config.json, pytorch.bin 이 제대로 있는지 확인 해보시면 좋을거 같습니다.

**Comment by haven-jeon** [comment]
PyTorch Lightning 1.2.1 기반으로 `README.md` 순서로 테스트 수행했을때 아무런 문제 없었습니다.

모델 저장 경로와 그 파라메터가 어떻게 흘러가는지 확인해보시면 해결하실 수 있을걸로 보입니다.

**Comment by SeungJun9164** [comment]
죄송하지만 이해가 잘 안되어서 질문드립니다.

현재 kobart_chit_chat.py 을 다운받아 개인컴퓨터에서 KoBART.py 라는 파일로 저장하였고 ArgsBase() 클래스에서 train, test경로를 개인컴퓨터에서 저장된 곳을 가르키게 설정하였습니다.

그런 후 cmd에서 실행하기 위해 
python KoBART.py --gradient_clip_val 1.0 --max_epochs 3 --default_root_dir logs --model_path /content/gdrive/MyDrive/kobart/kobart_from_pretrained/pytorch_model.bin --tokenizer_path /content/gdrive/MyDrive/kobart/emji_tokenizer --chat --gpus 1 
위와 같이 model_path와 tokenizer_path 경로를 직접 설정해주었습니다. 이렇게 실행하였을 때 디코딩오류가 발생하였습니다.
이러한 방식으로 직접적인 경로를 설정해주면 안되는 것인지 이해가 안되어서 질문드립니다.ㅠㅠ

**Comment by haven-jeon** [comment]
`--model_path`는 transformers 모델이 저장되는 directory를 가르켜야 됩니다. https://huggingface.co/transformers/main_classes/model.html#transformers.PreTrainedModel.from_pretrained 참고하시기 바랍니다.

**Comment by SeungJun9164** [comment]
감사합니다. 덕분에 해결하였습니다.

**Comment by SeungJun9164** [comment]
현재 KoBART-chatbot에서 제공해주시는 colab링크에서 실행하면 아래와 같은 오류가 발생합니다.

Traceback (most recent call last):
  File "kobart_chit_chat.py", line 7, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 62, in <module>
    from pytorch_lightning import metrics
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.functional.accuracy import _accuracy_compute, _accuracy_update
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/functional/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.functional.accuracy import accuracy  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/functional/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.classification.helpers import _input_format_classification, DataType
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/helpers.py", line 19, in <module>
    from pytorch_lightning.metrics.utils import select_topk, to_onehot
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 18, in <module>
    from pytorch_lightning.utilities import rank_zero_warn
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from torchtext.legacy.data import Batch
  File "/usr/local/lib/python3.7/dist-packages/torchtext/__init__.py", line 6, in <module>
    from . import experimental
  File "/usr/local/lib/python3.7/dist-packages/torchtext/experimental/__init__.py", line 2, in <module>
    from . import transforms
  File "/usr/local/lib/python3.7/dist-packages/torchtext/experimental/transforms.py", line 4, in <module>
    from torchtext._torchtext import RegexTokenizer as RegexTokenizerPybind
ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo

한번 봐주시면 감사하겠습니다.

**Comment by haven-jeon** [comment]
colab cuda가 업데이트 되면서 Pytorch 버전이 맞지 않게 되었네요. 
370ae8757ef2262ece50dacbfa5c842682683dc3 로 정상동작 확인 했습니다.

**Comment by SeungJun9164** [comment]
감사합니다
