### ISSUE TITLE
Argument Error for Embedding

### ISSUE THREAD

**Issue by HDKIMgithub** [haven-jeon/KoBART-chatbot#3]
Hello, 
Thanks for your sharing.
While I was following the instructions
for executing the KoBART chatbot application,
I got an error message from its training part.
It was executed on my local computer (Windows 10).
The following is the error message.
I would like to appreciate your help in advance. 
Kindly Yours

---------------------------------------- The error message --------------------------------------

KoBART-chatbot>python kobart_chit_chat.py  --gradient_clip_val 1.0 --max_epochs 3 --default_root_dir logs --model_path kobart_from_pretrained  --tokenizer_path emji_tokenizer --chat --gpus 1

INFO:root:Namespace(accelerator=None, accumulate_grad_batches=1, amp_backend='native', amp_level='O2', auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, automatic_optimization=None, batch_size=14, benchmark=False, chat=True, check_val_every_n_epoch=1, checkpoint_callback=True, checkpoint_path=None, default_root_dir='logs', deterministic=False, distributed_backend=None, enable_pl_optimizer=None, fast_dev_run=False, flush_logs_every_n_steps=100, gpus=1, gradient_clip_val=1.0, limit_predict_batches=1.0, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0, log_every_n_steps=50, log_gpu_memory=None, logger=True, lr=5e-05, max_epochs=3, max_seq_len=36, max_steps=None, min_epochs=None, min_steps=None, model_path='kobart_from_pretrained', move_metrics_to_cpu=False, multiple_trainloader_mode='max_size_cycle', num_nodes=1, num_processes=1, num_sanity_val_steps=2, num_workers=5, overfit_batches=0.0, plugins=None, precision=32, prepare_data_per_node=True, process_position=0, profiler=None, progress_bar_refresh_rate=None, reload_dataloaders_every_epoch=False, replace_sampler_ddp=True, resume_from_checkpoint=None, stochastic_weight_avg=False, sync_batchnorm=False, terminate_on_nan=False, test_file='Chatbot_data/test.csv', tokenizer_path='emji_tokenizer', tpu_cores=<function _gpus_arg_default at 0x000001A88E12C598>, track_grad_norm=-1, train_file='Chatbot_data/train.csv', truncated_bptt_steps=None, val_check_interval=1.0, warmup_ratio=0.1, weights_save_path=None, weights_summary='top')

GPU available: True, used: True

TPU available: False, using: 0 TPU cores

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

INFO:root:number of workers 1, data length 10640

INFO:root:num_train_steps : 2280

INFO:root:num_warmup_steps : 228

2021-03-31 15:51:39.988568: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll

 

  | Name  | Type                         | Params

-------------------------------------------------------

0 | model | BartForConditionalGeneration | 123 M

-------------------------------------------------------

123 M     Trainable params

0         Non-trainable params

123 M     Total params

495.440   Total estimated model params size (MB)

Validation sanity check:   0%|                                                                   | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):

  File "kobart_chit_chat.py", line 296, in <module>

    trainer.fit(model, dm)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 499, in fit

    self.dispatch()

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 546, in dispatch

    self.accelerator.start_training(self)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 73, in start_training

    self.training_type_plugin.start_training(trainer)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 114, in start_training

    self._results = trainer.run_train()

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 607, in run_train

    self.run_sanity_check(self.lightning_module)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 860, in run_sanity_check

    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 725, in run_evaluation

    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 166, in evaluation_step

    output = self.trainer.accelerator.validation_step(args)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 177, in validation_step

    return self.training_type_plugin.validation_step(*args)

  File "D:\Programs\Python\Python36\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 131, in validation_step

    return self.lightning_module.validation_step(*args, **kwargs)

  File "kobart_chit_chat.py", line 253, in validation_step

    outs = self(batch)

  File "D:\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl

    result = self.forward(*input, **kwargs)

  File "kobart_chit_chat.py", line 244, in forward

    labels=inputs['labels'], return_dict=True)

  File "D:\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl

    result = self.forward(*input, **kwargs)

  File "D:\Programs\Python\Python36\lib\site-packages\transformers\models\bart\modeling_bart.py", line 1295, in forward

    return_dict=return_dict,

  File "D:\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl

    result = self.forward(*input, **kwargs)

  File "D:\Programs\Python\Python36\lib\site-packages\transformers\models\bart\modeling_bart.py", line 1157, in forward

    return_dict=return_dict,

  File "D:\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl

    result = self.forward(*input, **kwargs)

  File "D:\Programs\Python\Python36\lib\site-packages\transformers\models\bart\modeling_bart.py", line 748, in forward

    inputs_embeds = self.embed_tokens(input_ids) * self.embed_scale

  File "D:\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl

    result = self.forward(*input, **kwargs)

  File "D:\Programs\Python\Python36\lib\site-packages\torch\nn\modules\sparse.py", line 126, in forward

    self.norm_type, self.scale_grad_by_freq, self.sparse)

  File "D:\Programs\Python\Python36\lib\site-packages\torch\nn\functional.py", line 1852, in embedding

    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)

**Comment by HDKIMgithub** [comment]
Finally I find that it is due to a problem of Windows 10.
Refer to the following url
https://stackoverflow.com/questions/56360644/pytorch-runtimeerror-expected-tensor-for-argument-1-indices-to-have-scalar-t
Have a nice day.

**Comment by haven-jeon** [comment]
@HDKIMgithub  적당한 윈도우 머신이 없어서 에러 재현에 어려움이 있었는데, 해결 하셨다니 다행이네요.
해당 이슈는 close 하도록 하겠습니다.

감사합니다.
